-- Mobile Device Registration Schema
-- Handles device registration via unique codes generated by admins

-- Device registration codes table
CREATE TABLE IF NOT EXISTS device_registration_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    code VARCHAR(20) UNIQUE NOT NULL, -- Unique 8-character code (generic, no role)
    created_by UUID NOT NULL REFERENCES users(id), -- Admin who generated it
    expires_at TIMESTAMP, -- Optional expiration
    is_used BOOLEAN DEFAULT false, -- Whether code has been used
    used_at TIMESTAMP, -- When code was used
    used_by_device_id VARCHAR(255), -- Device ID that used this code
    max_uses INTEGER DEFAULT 1, -- How many times code can be used (default 1)
    current_uses INTEGER DEFAULT 0, -- Current number of uses
    is_active BOOLEAN DEFAULT true, -- Admin can deactivate codes
    notes TEXT, -- Optional notes about this code
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Registered devices table
CREATE TABLE IF NOT EXISTS mobile_devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id VARCHAR(255) UNIQUE NOT NULL, -- Unique device identifier (Android ID or generated)
    device_name VARCHAR(255), -- User-friendly device name
    store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id), -- User assigned to this device (set by admin)
    assigned_by UUID REFERENCES users(id), -- Admin who assigned the user
    assigned_at TIMESTAMP, -- When user was assigned
    registration_code_id UUID REFERENCES device_registration_codes(id), -- Code used for registration
    fcm_token VARCHAR(255), -- Firebase Cloud Messaging token for push notifications
    last_sync_at TIMESTAMP, -- Last successful sync
    last_seen_at TIMESTAMP, -- Last time device was active
    is_active BOOLEAN DEFAULT true, -- Admin can deactivate devices
    is_locked BOOLEAN DEFAULT false, -- Remote lock capability
    locked_at TIMESTAMP, -- When device was locked
    locked_by UUID REFERENCES users(id), -- Who locked the device
    metadata JSONB, -- Device info (OS version, app version, etc.)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User device permissions (custom permissions per user-device assignment)
CREATE TABLE IF NOT EXISTS user_device_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id UUID NOT NULL REFERENCES mobile_devices(id) ON DELETE CASCADE,
    can_scan_barcode BOOLEAN DEFAULT true,
    can_adjust_inventory BOOLEAN DEFAULT true,
    can_create_orders BOOLEAN DEFAULT false,
    can_approve_orders BOOLEAN DEFAULT false,
    can_view_reports BOOLEAN DEFAULT false,
    can_edit_products BOOLEAN DEFAULT false,
    can_manage_devices BOOLEAN DEFAULT false,
    can_transfer_inventory BOOLEAN DEFAULT false,
    can_mark_damaged BOOLEAN DEFAULT true,
    can_receive_inventory BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, device_id)
);

-- Index for user device permissions
CREATE INDEX IF NOT EXISTS idx_user_device_permissions_user ON user_device_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_device_permissions_device ON user_device_permissions(device_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_device_codes_store ON device_registration_codes(store_id);
CREATE INDEX IF NOT EXISTS idx_device_codes_code ON device_registration_codes(code);
CREATE INDEX IF NOT EXISTS idx_device_codes_active ON device_registration_codes(store_id, is_active, is_used) WHERE is_active = true AND is_used = false;
CREATE INDEX IF NOT EXISTS idx_mobile_devices_store ON mobile_devices(store_id);
CREATE INDEX IF NOT EXISTS idx_mobile_devices_device_id ON mobile_devices(device_id);
CREATE INDEX IF NOT EXISTS idx_mobile_devices_user ON mobile_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_mobile_devices_active ON mobile_devices(store_id, is_active) WHERE is_active = true;

-- Function to generate unique code
CREATE OR REPLACE FUNCTION generate_device_code()
RETURNS VARCHAR(20) AS $$
DECLARE
    new_code VARCHAR(20);
    code_exists BOOLEAN;
BEGIN
    LOOP
        -- Generate 8-character alphanumeric code (uppercase, no confusing characters)
        new_code := upper(
            substring(
                md5(random()::text || clock_timestamp()::text) 
                from 1 for 8
            )
        );
        -- Replace confusing characters (0, O, I, 1, L)
        new_code := replace(replace(replace(replace(replace(new_code, '0', 'A'), 'O', 'B'), 'I', 'C'), '1', 'D'), 'L', 'E');
        
        -- Check if code exists
        SELECT EXISTS(SELECT 1 FROM device_registration_codes WHERE code = new_code) INTO code_exists;
        
        EXIT WHEN NOT code_exists;
    END LOOP;
    
    RETURN new_code;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at
CREATE TRIGGER update_device_codes_updated_at
    BEFORE UPDATE ON device_registration_codes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_mobile_devices_updated_at
    BEFORE UPDATE ON mobile_devices
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE device_registration_codes IS 'Generic registration codes for linking mobile devices to stores (no role specified)';
COMMENT ON TABLE mobile_devices IS 'Registered mobile devices linked to stores, with optional user assignment';
COMMENT ON TABLE user_device_permissions IS 'Custom permissions for each user-device assignment (set by admin)';

